//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyeensport.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
            this.SubPanertCategories = new HashSet<SubPanertCategory>();
        }
    
        public int maDanhMuc { get; set; }
        public string tenDanhMuc { get; set; }
        public string linkDanhMuc { get; set; }
        public string titleDanhMuc { get; set; }
        public string metaDescriptionDanhMuc { get; set; }
        public string metaKeywordsDanhMuc { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<bool> hienThi { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<SubPanertCategory> SubPanertCategories { get; set; }
    }
}
