//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyeensport.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int maNews { get; set; }
        public string tenNews { get; set; }
        public string linkNews { get; set; }
        public string titleNews { get; set; }
        public string metaDescriptionNews { get; set; }
        public string metaKeywordNews { get; set; }
        public Nullable<bool> hienThi { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
