//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyeensport.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubType
    {
        public int maProductSubType { get; set; }
        public string tenProductSubType { get; set; }
        public string iconProductSubType { get; set; }
        public string tenProductType { get; set; }
        public string tenDanhMuc { get; set; }
        public Nullable<bool> hienThi { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
