//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyeensport.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class Range
    {
        public int maRange { get; set; }
        public string tenRange { get; set; }
        public string linkRange { get; set; }
        public Nullable<bool> hienThi { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
