//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyeensport.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubPanertCategory
    {
        public SubPanertCategory()
        {
            this.SubChildCategories = new HashSet<SubChildCategory>();
        }
    
        public int maDanhMucCon { get; set; }
        public Nullable<int> maDanhMuc { get; set; }
        public string tenDanhMucCon { get; set; }
        public Nullable<int> viTri { get; set; }
        public string anhBiaDesktop { get; set; }
        public string anhBiaMobile { get; set; }
        public string linkDanhMucCon { get; set; }
        public string titleDanhMucCon { get; set; }
        public string metaDescriptionDanhMucCon { get; set; }
        public string metaKeywordsDanhMucCon { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<bool> hienThi { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<SubChildCategory> SubChildCategories { get; set; }
    }
}
